CREATE TABLE [rpt].[dimRegion] (
    [RegionKey]          INT            IDENTITY (1, 1) NOT NULL,
    [Country_ID]         INT            NOT NULL,
    [State_ID]           INT            NOT NULL,
    [City_ID]            INT            NOT NULL,
    [Country]            VARCHAR (200)  NOT NULL,
    [Country_Code]       VARCHAR (2)    NOT NULL,
    [Country_Code2]      VARCHAR (3)    NULL,
    [Country_GeoName_ID] INT            NULL,
    [Continent]          VARCHAR (2)    NULL,
    [State]              VARCHAR (200)  NOT NULL,
    [State_GeoName_ID]   INT            NULL,
    [State_Code]         VARCHAR (50)   NULL,
    [City]               VARCHAR (200)  NOT NULL,
    [City_GeoName_ID]    INT            NULL,
    [Latitude]           NUMERIC (8, 5) NULL,
    [Longitude]          NUMERIC (8, 5) NULL,
    [Population]         BIGINT         NULL,
    [LastUpdatedBy]      VARCHAR (40)   CONSTRAINT [DF_dimRegion_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]       DATETIME       CONSTRAINT [DF_dimRegion_LastModified] DEFAULT (getdate()) NULL,
    [IsActive]           BIT            CONSTRAINT [DF_dimRegion_IsActive] DEFAULT ((1)) NULL,
    [StartDate]          DATETIME       CONSTRAINT [DF_dimRegion_StartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]            DATETIME       CONSTRAINT [DF_dimRegion_EndDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    PRIMARY KEY CLUSTERED ([RegionKey] ASC)
);

