CREATE TABLE [rpt].[tblFactAICPExamScores] (
    [MemberIDKey]             INT          NOT NULL,
    [SEQN]                    INT          NOT NULL,
    [ExamIDKey]               INT          NOT NULL,
    [RegistrantTypeIDKey]     INT          NOT NULL,
    [MemberTypeIDKey]         INT          NOT NULL,
    [ChapterKey]              INT          NOT NULL,
    [SalaryIDKey]             INT          NOT NULL,
    [RaceIDKey]               INT          NOT NULL,
    [StatusKey]               INT          NOT NULL,
    [MemberStatusKey]         INT          NOT NULL,
    [AddressNum1Key]          INT          NULL,
    [AddressNum2Key]          INT          NOT NULL,
    [ScaledScore]             INT          NOT NULL,
    [RawScore]                INT          NULL,
    [Section_AreasOfPractice] INT          NOT NULL,
    [Section_PlanMaking]      INT          NOT NULL,
    [Section_PlanKnowledge]   INT          NOT NULL,
    [Section_CodeOfEthics]    INT          NOT NULL,
    [Section_Leadership]      INT          NOT NULL,
    [Pass]                    INT          NOT NULL,
    [LastUpdatedBy]           VARCHAR (40) DEFAULT (suser_sname()) NULL,
    [LastModified]            DATETIME     DEFAULT (getdate()) NULL,
    FOREIGN KEY ([AddressNum1Key]) REFERENCES [rpt].[dimAddress] ([Address_Key]),
    FOREIGN KEY ([AddressNum2Key]) REFERENCES [rpt].[dimAddress] ([Address_Key]),
    FOREIGN KEY ([ChapterKey]) REFERENCES [rpt].[dimChapter] ([ChapterKey]),
    FOREIGN KEY ([ExamIDKey]) REFERENCES [rpt].[dimAICPExam] ([ExamIDKey]),
    FOREIGN KEY ([MemberIDKey]) REFERENCES [rpt].[dimMember] ([MemberIDKey]),
    FOREIGN KEY ([MemberStatusKey]) REFERENCES [rpt].[dimMemberStatus] ([MemberStatusKey]),
    FOREIGN KEY ([MemberTypeIDKey]) REFERENCES [rpt].[dimMemberType] ([MemberTypeIDKey]),
    FOREIGN KEY ([RaceIDKey]) REFERENCES [rpt].[dimRace] ([RaceIDKey]),
    FOREIGN KEY ([SalaryIDKey]) REFERENCES [rpt].[dimSalary] ([SalaryIDKey]),
    FOREIGN KEY ([StatusKey]) REFERENCES [rpt].[dimStatus] ([StatusKey])
);

