CREATE TABLE [stg].[Cadmium_Abstracts] (
    [SubmissionID]           NVARCHAR (24)   NULL,
    [SubmitterID]            NVARCHAR (24)   NULL,
    [AbstractID]             NVARCHAR (24)   NULL,
    [AbstractTopic]          NVARCHAR (188)  NULL,
    [AbstractTopicAlt]       NVARCHAR (80)   NULL,
    [AbstractSubTopic]       NVARCHAR (4000) NULL,
    [AbstractText0]          NVARCHAR (4000) NULL,
    [AbstractText1]          NVARCHAR (MAX)  NULL,
    [AbstractText2]          NVARCHAR (MAX)  NULL,
    [AbstractText3]          NVARCHAR (4000) NULL,
    [AbstractText4]          NVARCHAR (200)  NULL,
    [AbstractText5]          NVARCHAR (200)  NULL,
    [AbstractText11]         NVARCHAR (200)  NULL,
    [AbstractText12]         NVARCHAR (200)  NULL,
    [AbstractText13]         NVARCHAR (200)  NULL,
    [AbstractText14]         NVARCHAR (200)  NULL,
    [AbstractText15]         NVARCHAR (200)  NULL,
    [AbstractText16]         NVARCHAR (200)  NULL,
    [AbstractText27]         NVARCHAR (200)  NULL,
    [AbstractText28]         NVARCHAR (200)  NULL,
    [AbstractText29]         NVARCHAR (200)  NULL,
    [AbstractText30]         NVARCHAR (200)  NULL,
    [AbstractText31]         NVARCHAR (200)  NULL,
    [AbstractText32]         NVARCHAR (200)  NULL,
    [AbstractText33]         NVARCHAR (200)  NULL,
    [AbstractText34]         NVARCHAR (200)  NULL,
    [AbstractText35]         NVARCHAR (200)  NULL,
    [AbstractText36]         NVARCHAR (200)  NULL,
    [AbstractTargetAudience] NVARCHAR (500)  NULL,
    [AbstractJobFunction]    NVARCHAR (200)  NULL,
    [AbstractPickList]       NVARCHAR (200)  NULL,
    [TargetAudienceOther]    NVARCHAR (200)  NULL,
    [JobFunctionOther]       NVARCHAR (200)  NULL,
    [PickListOther]          NVARCHAR (200)  NULL,
    [AbstractQuestion1]      NVARCHAR (200)  NULL,
    [AbstractQuestion2]      NVARCHAR (200)  NULL,
    [AbstractQuestion3]      NVARCHAR (200)  NULL,
    [AbstractQuestion4]      NVARCHAR (200)  NULL,
    [LastUpdatedBy]          VARCHAR (40)    CONSTRAINT [df_Adbstracts_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]           DATETIME        CONSTRAINT [df_Abstracts_LastModified] DEFAULT (getdate()) NULL
);

