CREATE TABLE [stg].[dj_conference_microsite] (
    [id]                              INT           NOT NULL,
    [is_npc]                          BIT           NOT NULL,
    [short_title]                     VARCHAR (50)  NULL,
    [url_path_stem]                   VARCHAR (50)  NOT NULL,
    [home_page_code]                  VARCHAR (50)  NOT NULL,
    [show_skip_to_dates]              BIT           NOT NULL,
    [status]                          VARCHAR (5)   NOT NULL,
    [deactivation_date]               DATETIME      NULL,
    [header_ad]                       TEXT          NULL,
    [sidebar_ad]                      TEXT          NULL,
    [footer_ad]                       TEXT          NULL,
    [custom_color]                    VARCHAR (50)  NULL,
    [hero_image_path]                 VARCHAR (100) NOT NULL,
    [home_summary_blurb]              TEXT          NULL,
    [signpost_logo_image_path]        VARCHAR (100) NOT NULL,
    [program_blurb]                   TEXT          NULL,
    [nosidebar_breakout_image_path]   VARCHAR (100) NOT NULL,
    [details_local_blurb]             TEXT          NULL,
    [event_master_id]                 INT           NULL,
    [home_page_id]                    INT           NULL,
    [search_filters_id]               INT           NULL,
    [interactive_educational_session] TEXT          NULL,
    [text_blurb_one]                  TEXT          NULL,
    [updated_time]                    DATETIME      NULL,
    [created_time]                    DATETIME      NULL,
    [LastUpdatedBy]                   VARCHAR (40)  CONSTRAINT [df_conference_microsite_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]                    DATETIME      CONSTRAINT [df_conference_microsite_LastModified] DEFAULT (getdate()) NULL,
    CONSTRAINT [conference_microsite_pkey] PRIMARY KEY CLUSTERED ([id] ASC)
);

