CREATE TABLE [stg].[dj_jobs_job] (
    [content_ptr_id]              INT             NOT NULL,
    [user_address_num]            INT             NULL,
    [address1]                    VARCHAR (40)    NULL,
    [address2]                    VARCHAR (40)    NULL,
    [city]                        VARCHAR (40)    NULL,
    [state]                       VARCHAR (100)   NULL,
    [zip_code]                    VARCHAR (10)    NULL,
    [country]                     VARCHAR (100)   NULL,
    [job_type]                    VARCHAR (50)    NOT NULL,
    [display_contact_info]        BIT             NOT NULL,
    [contact_us_first_name]       VARCHAR (20)    NULL,
    [contact_us_last_name]        VARCHAR (30)    NULL,
    [contact_us_email]            VARCHAR (100)   NULL,
    [contact_us_phone]            VARCHAR (20)    NULL,
    [company]                     VARCHAR (80)    NULL,
    [contact_us_address1]         VARCHAR (40)    NULL,
    [contact_us_address2]         VARCHAR (40)    NULL,
    [contact_us_city]             VARCHAR (40)    NULL,
    [contact_us_country]          VARCHAR (100)   NULL,
    [contact_us_state]            VARCHAR (15)    NULL,
    [contact_us_user_address_num] INT             NULL,
    [contact_us_zip_code]         VARCHAR (10)    NULL,
    [salary_range]                VARCHAR (50)    NULL,
    [post_time]                   DATETIME        NULL,
    [legacy_id]                   INT             NULL,
    [voter_voice_checksum]        VARCHAR (100)   NULL,
    [latitude]                    NUMERIC (10, 6) NULL,
    [longitude]                   NUMERIC (10, 6) NULL,
    [zip_code_extension]          VARCHAR (4)     NULL,
    [LastUpdatedBy]               VARCHAR (40)    CONSTRAINT [df_jobs_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]                DATETIME        CONSTRAINT [df_jobs_LastModified] DEFAULT (getdate()) NULL,
    CONSTRAINT [jobs_job_pkey] PRIMARY KEY CLUSTERED ([content_ptr_id] ASC)
);

