CREATE TABLE [stg].[Fact_Events] (
    [Event_ID]               INT            NOT NULL,
    [Master_ID]              INT            NOT NULL,
    [Parent_Master_ID]       INT            NULL,
    [Event_Type]             VARCHAR (50)   NOT NULL,
    [Title]                  VARCHAR (200)  NULL,
    [Status]                 VARCHAR (5)    NOT NULL,
    [Address1]               VARCHAR (40)   NULL,
    [Address2]               VARCHAR (40)   NULL,
    [City]                   VARCHAR (40)   NULL,
    [State]                  VARCHAR (100)  NULL,
    [Zip_Code]               VARCHAR (10)   NULL,
    [Country]                VARCHAR (100)  NULL,
    [Begin_Time]             DATETIME       NULL,
    [End_Time]               DATETIME       NULL,
    [Is_Online]              BIT            NULL,
    [CM_Status]              VARCHAR (5)    NOT NULL,
    [CM_Requested]           NUMERIC (6, 2) NULL,
    [CM_Approved]            NUMERIC (6, 2) NULL,
    [CM_Law_Requested]       NUMERIC (6, 2) NULL,
    [CM_Law_Approved]        NUMERIC (6, 2) NULL,
    [Is_Free]                BIT            NOT NULL,
    [Length_In_Minutes]      INT            NULL,
    [Timezone]               VARCHAR (50)   NULL,
    [Harvester_External_Key] INT            NULL,
    [Provider_ID]            VARCHAR (10)   NOT NULL,
    [LastUpdatedBy]          VARCHAR (40)   CONSTRAINT [df_Fact_Events_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]           DATETIME       CONSTRAINT [df_Fact_Events_LastModified] DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([Event_ID] ASC)
);

