CREATE TABLE [stg].[imis_Member_Types] (
    [MEMBER_TYPE]            VARCHAR (5)     CONSTRAINT [DF_Member_Types_MEMBER_TYPE] DEFAULT ('') NOT NULL,
    [DESCRIPTION]            VARCHAR (20)    CONSTRAINT [DF_Member_Types_DESCRIPTION] DEFAULT ('') NOT NULL,
    [MEMBER_RECORD]          BIT             CONSTRAINT [DF_Member_Types_MEMBER_RECORD] DEFAULT ((0)) NOT NULL,
    [COMPANY_RECORD]         BIT             CONSTRAINT [DF_Member_Types_COMPANY_RECORD] DEFAULT ((0)) NOT NULL,
    [DUES_CODE_1]            VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_1] DEFAULT ('') NOT NULL,
    [DUES_CODE_2]            VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_2] DEFAULT ('') NOT NULL,
    [DUES_CODE_3]            VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_3] DEFAULT ('') NOT NULL,
    [DUES_CODE_4]            VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_4] DEFAULT ('') NOT NULL,
    [DUES_CODE_5]            VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_5] DEFAULT ('') NOT NULL,
    [DUES_CODE_6]            VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_6] DEFAULT ('') NOT NULL,
    [DUES_CODE_7]            VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_7] DEFAULT ('') NOT NULL,
    [DUES_CODE_8]            VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_8] DEFAULT ('') NOT NULL,
    [DUES_CODE_9]            VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_9] DEFAULT ('') NOT NULL,
    [DUES_CODE_10]           VARCHAR (31)    CONSTRAINT [DF_Member_Types_DUES_CODE_10] DEFAULT ('') NOT NULL,
    [RATE_1]                 NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_1] DEFAULT ((0)) NOT NULL,
    [RATE_2]                 NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_2] DEFAULT ((0)) NOT NULL,
    [RATE_3]                 NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_3] DEFAULT ((0)) NOT NULL,
    [RATE_4]                 NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_4] DEFAULT ((0)) NOT NULL,
    [RATE_5]                 NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_5] DEFAULT ((0)) NOT NULL,
    [RATE_6]                 NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_6] DEFAULT ((0)) NOT NULL,
    [RATE_7]                 NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_7] DEFAULT ((0)) NOT NULL,
    [RATE_8]                 NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_8] DEFAULT ((0)) NOT NULL,
    [RATE_9]                 NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_9] DEFAULT ((0)) NOT NULL,
    [RATE_10]                NUMERIC (15, 2) CONSTRAINT [DF_Member_Types_RATE_10] DEFAULT ((0)) NOT NULL,
    [BILL_COMPANY]           BIT             CONSTRAINT [DF_Member_Types_BILL_COMPANY] DEFAULT ((0)) NOT NULL,
    [SPECIAL_FORM]           VARCHAR (43)    CONSTRAINT [DF_Member_Types_SPECIAL_FORM] DEFAULT ('') NOT NULL,
    [COMP_1]                 BIT             CONSTRAINT [DF_Member_Types_COMP_1] DEFAULT ((0)) NOT NULL,
    [COMP_2]                 BIT             CONSTRAINT [DF_Member_Types_COMP_2] DEFAULT ((0)) NOT NULL,
    [COMP_3]                 BIT             CONSTRAINT [DF_Member_Types_COMP_3] DEFAULT ((0)) NOT NULL,
    [COMP_4]                 BIT             CONSTRAINT [DF_Member_Types_COMP_4] DEFAULT ((0)) NOT NULL,
    [COMP_5]                 BIT             CONSTRAINT [DF_Member_Types_COMP_5] DEFAULT ((0)) NOT NULL,
    [COMP_6]                 BIT             CONSTRAINT [DF_Member_Types_COMP_6] DEFAULT ((0)) NOT NULL,
    [COMP_7]                 BIT             CONSTRAINT [DF_Member_Types_COMP_7] DEFAULT ((0)) NOT NULL,
    [COMP_8]                 BIT             CONSTRAINT [DF_Member_Types_COMP_8] DEFAULT ((0)) NOT NULL,
    [COMP_9]                 BIT             CONSTRAINT [DF_Member_Types_COMP_9] DEFAULT ((0)) NOT NULL,
    [COMP_10]                BIT             CONSTRAINT [DF_Member_Types_COMP_10] DEFAULT ((0)) NOT NULL,
    [DEFAULT_SECURITY_GROUP] VARCHAR (30)    NULL,
    [TIME_STAMP]             BIGINT          NULL,
    [Id_Identitycolumn]      INT             IDENTITY (1, 1) NOT NULL,
    [LastUpdatedBy]          VARCHAR (40)    CONSTRAINT [df_Member_Types_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]           DATETIME        CONSTRAINT [df_Member_Types_LastModified] DEFAULT (getdate()) NULL,
    [IsActive]               BIT             NULL,
    [StartDate]              DATETIME        CONSTRAINT [df_Member_Types_StartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]                DATETIME        CONSTRAINT [df_Member_Types_EndtDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_Member_Types] PRIMARY KEY CLUSTERED ([Id_Identitycolumn] ASC)
);

