CREATE TABLE [stg].[imis_Product_Function] (
    [PRODUCT_CODE]                 VARCHAR (31)    CONSTRAINT [DF_Product_Function_PRODUCT_CODE] DEFAULT ('') NOT NULL,
    [FUNCTION_TYPE]                VARCHAR (5)     CONSTRAINT [DF_Product_Function_FUNCTION_TYPE] DEFAULT ('') NOT NULL,
    [BEGIN_DATE_TIME]              DATETIME        NULL,
    [END_DATE_TIME]                DATETIME        NULL,
    [SEQ]                          INT             CONSTRAINT [DF_Product_Function_SEQ] DEFAULT ((0)) NOT NULL,
    [MINIMUM_ATTENDANCE]           INT             CONSTRAINT [DF_Product_Function_MINIMUM_ATTENDANCE] DEFAULT ((0)) NOT NULL,
    [EXPECTED_ATTENDANCE]          INT             CONSTRAINT [DF_Product_Function_EXPECTED_ATTENDANCE] DEFAULT ((0)) NOT NULL,
    [GUARANTEED_ATTENDANCE]        INT             CONSTRAINT [DF_Product_Function_GUARANTEED_ATTENDANCE] DEFAULT ((0)) NOT NULL,
    [ACTUAL_ATTENDANCE]            INT             CONSTRAINT [DF_Product_Function_ACTUAL_ATTENDANCE] DEFAULT ((0)) NOT NULL,
    [SETTINGS]                     INT             CONSTRAINT [DF_Product_Function_SETTINGS] DEFAULT ((0)) NOT NULL,
    [SETUP_DATE_TIME]              DATETIME        NULL,
    [POST_DATE_TIME]               DATETIME        NULL,
    [AUTO_ENROLL]                  BIT             CONSTRAINT [DF_Product_Function_AUTO_ENROLL] DEFAULT ((0)) NOT NULL,
    [PRINT_TICKET]                 BIT             CONSTRAINT [DF_Product_Function_PRINT_TICKET] DEFAULT ((0)) NOT NULL,
    [LAST_TICKET]                  INT             CONSTRAINT [DF_Product_Function_LAST_TICKET] DEFAULT ((0)) NOT NULL,
    [CEU_TYPE]                     VARCHAR (15)    CONSTRAINT [DF_Product_Function_CEU_TYPE] DEFAULT ('') NOT NULL,
    [CEU_AMOUNT]                   NUMERIC (15, 2) CONSTRAINT [DF_Product_Function_CEU_AMOUNT] DEFAULT ((0)) NOT NULL,
    [COURSE_CODE]                  VARCHAR (15)    CONSTRAINT [DF_Product_Function_COURSE_CODE] DEFAULT ('') NOT NULL,
    [OTHER_TICKETS]                VARCHAR (255)   CONSTRAINT [DF_Product_Function_OTHER_TICKETS] DEFAULT ('') NOT NULL,
    [CEU_ENTERED]                  BIT             CONSTRAINT [DF_Product_Function_CEU_ENTERED] DEFAULT ((0)) NOT NULL,
    [MAXIMUM_ATTENDANCE]           INT             CONSTRAINT [DF_Product_Function_MAXIMUM_ATTENDANCE] DEFAULT ((0)) NOT NULL,
    [PARENT]                       BIT             CONSTRAINT [DF_Product_Function_PARENT] DEFAULT ((0)) NOT NULL,
    [CONFLICT_CODE]                VARCHAR (10)    CONSTRAINT [DF_Product_Function_CONFLICT_CODE] DEFAULT ('') NOT NULL,
    [WEB_ENABLED]                  BIT             CONSTRAINT [DF_Product_Function_WEB_ENABLED] DEFAULT ((0)) NOT NULL,
    [WEB_MULTI_REG]                TINYINT         CONSTRAINT [DF_Product_Function_WEB_MULTI_REG] DEFAULT ((0)) NOT NULL,
    [SQUARE_FEET]                  NUMERIC (15, 2) NULL,
    [IS_FR_ITEM]                   BIT             CONSTRAINT [DF_Product_Function_IS_FR_ITEM] DEFAULT ((0)) NOT NULL,
    [IS_GUEST_FUNCTION]            BIT             CONSTRAINT [DF_Product_Function_IS_GUEST_FUNCTION] DEFAULT ('0') NOT NULL,
    [CREATE_DETAIL_ACTIVITY]       BIT             CONSTRAINT [DF_Product_Function_CREATE_DETAIL_ACTIVITY] DEFAULT ('0') NOT NULL,
    [EVENT_TRACK]                  VARCHAR (255)   CONSTRAINT [DF_Product_Function_EVENT_TRACK] DEFAULT ('') NOT NULL,
    [EVENT_CATEGORY]               VARCHAR (255)   CONSTRAINT [DF_Product_Function_EVENT_CATEGORY] DEFAULT ('') NOT NULL,
    [IS_EVENT_REGISTRATION_OPTION] BIT             CONSTRAINT [DF_Product_Function_IS_EVENT_REGISTRATION_OPTION] DEFAULT ((0)) NOT NULL,
    [FORM_DEFINITION_SECTION_ID]   VARCHAR (36)    CONSTRAINT [DF_Product_Function_Form_Definition_Section_ID] DEFAULT ('') NOT NULL,
    [AVAILABLE_TO]                 INT             CONSTRAINT [DF_Product_Function_AVAILABLE_TO] DEFAULT ((0)) NOT NULL,
    [ENABLE_TIME_CONFLICTS]        BIT             CONSTRAINT [DF_Product_Function_Enable_Time_Conflicts] DEFAULT ((0)) NOT NULL,
    [WEB_CONFLICT_CODES]           VARCHAR (255)   NULL,
    [TIME_STAMP]                   BIGINT          NULL,
    [Id_Identitycolumn]            INT             IDENTITY (1, 1) NOT NULL,
    [LastUpdatedBy]                VARCHAR (40)    CONSTRAINT [df_Product_Function_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]                 DATETIME        CONSTRAINT [df_Product_Function_LastModified] DEFAULT (getdate()) NULL,
    [IsActive]                     BIT             NULL,
    [StartDate]                    DATETIME        CONSTRAINT [df_Product_Function_StartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]                      DATETIME        CONSTRAINT [df_Product_Function_EndtDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_Product_Function] PRIMARY KEY CLUSTERED ([Id_Identitycolumn] ASC)
);

