CREATE TABLE [stg].[imis_Order_Lines] (
    [ORDER_NUMBER]                 NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_ORDER_NUMBER] DEFAULT ((0)) NOT NULL,
    [LINE_NUMBER]                  NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_LINE_NUMBER] DEFAULT ((0)) NOT NULL,
    [PRODUCT_CODE]                 VARCHAR (31)    CONSTRAINT [DF_Order_Lines_PRODUCT_CODE] DEFAULT ('') NOT NULL,
    [LOCATION]                     VARCHAR (10)    CONSTRAINT [DF_Order_Lines_LOCATION] DEFAULT ('') NOT NULL,
    [LOT_SERIAL]                   VARCHAR (20)    CONSTRAINT [DF_Order_Lines_LOT_SERIAL] DEFAULT ('') NOT NULL,
    [DESCRIPTION]                  VARCHAR (255)   CONSTRAINT [DF_Order_Lines_DESCRIPTION] DEFAULT ('') NOT NULL,
    [QUANTITY_ORDERED]             NUMERIC (15, 6) CONSTRAINT [DF_Order_Lines_QUANTITY_ORDERED] DEFAULT ((0)) NOT NULL,
    [QUANTITY_SHIPPED]             NUMERIC (15, 6) CONSTRAINT [DF_Order_Lines_QUANTITY_SHIPPED] DEFAULT ((0)) NOT NULL,
    [QUANTITY_BACKORDERED]         NUMERIC (15, 6) CONSTRAINT [DF_Order_Lines_QUANTITY_BACKORDERED] DEFAULT ((0)) NOT NULL,
    [QUANTITY_RESERVED]            NUMERIC (15, 6) CONSTRAINT [DF_Order_Lines_QUANTITY_RESERVED] DEFAULT ((0)) NOT NULL,
    [QUANTITY_COMMITTED]           NUMERIC (15, 6) CONSTRAINT [DF_Order_Lines_QUANTITY_COMMITTED] DEFAULT ((0)) NOT NULL,
    [NUMBER_DAYS]                  INT             CONSTRAINT [DF_Order_Lines_NUMBER_DAYS] DEFAULT ((0)) NOT NULL,
    [TAXABLE]                      BIT             CONSTRAINT [DF_Order_Lines_TAXABLE] DEFAULT ((0)) NOT NULL,
    [TAXABLE_2]                    BIT             CONSTRAINT [DF_Order_Lines_TAXABLE_2] DEFAULT ((0)) NOT NULL,
    [UNIT_PRICE]                   MONEY           CONSTRAINT [DF_Order_Lines_UNIT_PRICE] DEFAULT ((0)) NOT NULL,
    [UNIT_COST]                    MONEY           CONSTRAINT [DF_Order_Lines_UNIT_COST] DEFAULT ((0)) NOT NULL,
    [UNDISCOUNTED_PRICE]           MONEY           CONSTRAINT [DF_Order_Lines_UNDISCOUNTED_PRICE] DEFAULT ((0)) NOT NULL,
    [EXTENDED_AMOUNT]              MONEY           CONSTRAINT [DF_Order_Lines_EXTENDED_AMOUNT] DEFAULT ((0)) NOT NULL,
    [EXTENDED_COST]                MONEY           CONSTRAINT [DF_Order_Lines_EXTENDED_COST] DEFAULT ((0)) NOT NULL,
    [UNDISCOUNTED_EXTENDED_AMOUNT] MONEY           CONSTRAINT [DF_Order_Lines_UNDISCOUNTED_EXTENDED_AMOUNT] DEFAULT ((0)) NOT NULL,
    [CANCEL_CODE]                  VARCHAR (10)    CONSTRAINT [DF_Order_Lines_CANCEL_CODE] DEFAULT ('') NOT NULL,
    [CANCEL_QUANTITY]              NUMERIC (15, 6) CONSTRAINT [DF_Order_Lines_CANCEL_QUANTITY] DEFAULT ((0)) NOT NULL,
    [COMMISSION_RATE]              NUMERIC (15, 4) CONSTRAINT [DF_Order_Lines_COMMISSION_RATE] DEFAULT ((0)) NOT NULL,
    [COMMISSION_AMOUNT]            MONEY           CONSTRAINT [DF_Order_Lines_COMMISSION_AMOUNT] DEFAULT ((0)) NOT NULL,
    [CEU_TYPE]                     VARCHAR (15)    CONSTRAINT [DF_Order_Lines_CEU_TYPE] DEFAULT ('') NOT NULL,
    [CEU_AWARDED]                  NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_CEU_AWARDED] DEFAULT ((0)) NOT NULL,
    [PASS_FAIL]                    VARCHAR (5)     CONSTRAINT [DF_Order_Lines_PASS_FAIL] DEFAULT ('') NOT NULL,
    [DATE_CONFIRMED]               DATETIME        NULL,
    [TICKETS_PRINTED]              INT             CONSTRAINT [DF_Order_Lines_TICKETS_PRINTED] DEFAULT ((0)) NOT NULL,
    [BOOTH_NUMBERS]                VARCHAR (255)   CONSTRAINT [DF_Order_Lines_BOOTH_NUMBERS] DEFAULT ('') NOT NULL,
    [NOTE]                         VARCHAR (255)   NULL,
    [INCOME_ACCOUNT]               VARCHAR (50)    CONSTRAINT [DF_Order_Lines_INCOME_ACCOUNT] DEFAULT ('') NOT NULL,
    [UNIT_WEIGHT]                  NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_UNIT_WEIGHT] DEFAULT ((0)) NOT NULL,
    [EXTENDED_WEIGHT]              NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_EXTENDED_WEIGHT] DEFAULT ((0)) NOT NULL,
    [PST_TAXABLE]                  BIT             CONSTRAINT [DF_Order_Lines_PST_TAXABLE] DEFAULT ((0)) NOT NULL,
    [IS_GST_TAXABLE]               BIT             CONSTRAINT [DF_Order_Lines_IS_GST_TAXABLE] DEFAULT ((0)) NOT NULL,
    [ADDED_TO_WAIT_LIST]           DATETIME        NULL,
    [BIN]                          VARCHAR (10)    CONSTRAINT [DF_Order_Lines_BIN] DEFAULT ('') NOT NULL,
    [TAX_AUTHORITY]                VARCHAR (15)    CONSTRAINT [DF_Order_Lines_TAX_AUTHORITY] DEFAULT ('') NOT NULL,
    [TAX_RATE]                     NUMERIC (15, 4) CONSTRAINT [DF_Order_Lines_TAX_RATE] DEFAULT ((0)) NOT NULL,
    [TAX_1]                        NUMERIC (15, 4) CONSTRAINT [DF_Order_Lines_TAX_1] DEFAULT ((0)) NOT NULL,
    [KIT_ITEM_TYPE]                TINYINT         CONSTRAINT [DF_Order_Lines_KIT_ITEM_TYPE] DEFAULT ((0)) NOT NULL,
    [DISCOUNT]                     NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_DISCOUNT] DEFAULT ((0)) NOT NULL,
    [UF_1]                         VARCHAR (30)    CONSTRAINT [DF_Order_Lines_UF_1] DEFAULT ('') NOT NULL,
    [UF_2]                         VARCHAR (30)    CONSTRAINT [DF_Order_Lines_UF_2] DEFAULT ('') NOT NULL,
    [UF_3]                         VARCHAR (30)    CONSTRAINT [DF_Order_Lines_UF_3] DEFAULT ('') NOT NULL,
    [UF_4]                         VARCHAR (30)    CONSTRAINT [DF_Order_Lines_UF_4] DEFAULT ('') NOT NULL,
    [EXTENDED_SQUARE_FEET]         NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_EXTENDED_SQUARE_FEET] DEFAULT ((0)) NOT NULL,
    [SQUARE_FEET]                  NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_SQUARE_FEET] DEFAULT ((0)) NOT NULL,
    [MEET_APPEAL]                  VARCHAR (40)    CONSTRAINT [DF_Order_Lines_MEET_APPEAL] DEFAULT ('') NOT NULL,
    [MEET_CAMPAIGN]                VARCHAR (10)    CONSTRAINT [DF_Order_Lines_MEET_CAMPAIGN] DEFAULT ('') NOT NULL,
    [FAIR_MARKET_VALUE]            NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_FAIR_MARKET_VALUE] DEFAULT ((0)) NOT NULL,
    [ORG_CODE]                     VARCHAR (5)     CONSTRAINT [DF_Order_Lines_ORG_CODE] DEFAULT ('') NOT NULL,
    [IS_FR_ITEM]                   BIT             CONSTRAINT [DF_Order_Lines_IS_FR_ITEM] DEFAULT ((0)) NOT NULL,
    [MANUAL_PRICE]                 NUMERIC (15, 2) CONSTRAINT [DF_Order_Lines_MANUAL_PRICE] DEFAULT ((0)) NOT NULL,
    [IS_MANUAL_PRICE]              BIT             CONSTRAINT [DF_Order_Lines_IS_MANUAL_PRICE] DEFAULT ((0)) NOT NULL,
    [UNIT_TAX_AMOUNT]              NUMERIC (15, 4) CONSTRAINT [DF_Order_Lines_UNIT_TAX_AMOUNT] DEFAULT ((0)) NOT NULL,
    [PRICE_FROM_COMPONENTS]        BIT             CONSTRAINT [DF_Order_Lines_PRICE_FROM_COMPONENTS] DEFAULT ((0)) NOT NULL,
    [QUANTITY_PER_KIT]             NUMERIC (15, 6) CONSTRAINT [DF_Order_Lines_QUANTITY_PER_KIT] DEFAULT ((0)) NOT NULL,
    [DISCOUNT_CODE]                VARCHAR (50)    NULL,
    [TIME_STAMP]                   BIGINT          NULL,
    [Id_Identitycolumn]            INT             IDENTITY (1, 1) NOT NULL,
    [LastUpdatedBy]                VARCHAR (40)    CONSTRAINT [df_Order_Lines_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]                 DATETIME        CONSTRAINT [df_Order_Lines_LastModified] DEFAULT (getdate()) NULL,
    [IsActive]                     BIT             NULL,
    [StartDate]                    DATETIME        CONSTRAINT [df_Order_Lines_StartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]                      DATETIME        CONSTRAINT [df_Order_Lines_EndDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_Order_Lines] PRIMARY KEY CLUSTERED ([ORDER_NUMBER] ASC, [LINE_NUMBER] ASC)
);

