CREATE TABLE [stg].[imis_UserMain] (
    [UserKey]                   UNIQUEIDENTIFIER CONSTRAINT [DF_UserMain_UserKey] DEFAULT (newid()) NOT NULL,
    [ContactMaster]             VARCHAR (100)    NULL,
    [UserId]                    VARCHAR (60)     CONSTRAINT [DF_UserMain_UserId] DEFAULT ('') NOT NULL,
    [IsDisabled]                BIT              CONSTRAINT [DF_UserMain_IsDisabled] DEFAULT ((1)) NOT NULL,
    [EffectiveDate]             DATETIME         NOT NULL,
    [ExpirationDate]            DATETIME         NULL,
    [UpdatedByUserKey]          UNIQUEIDENTIFIER NOT NULL,
    [UpdatedOn]                 DATETIME         NOT NULL,
    [CreatedByUserKey]          UNIQUEIDENTIFIER NOT NULL,
    [CreatedOn]                 DATETIME         NOT NULL,
    [MarkedForDeleteOn]         DATETIME         NULL,
    [DefaultDepartmentGroupKey] UNIQUEIDENTIFIER NOT NULL,
    [DefaultPerspectiveKey]     UNIQUEIDENTIFIER NOT NULL,
    [ProviderKey]               NVARCHAR (100)   NULL,
    [MultiFactorInfo]           NVARCHAR (MAX)   NULL,
    [Id_Identitycolumn]         INT              IDENTITY (1, 1) NOT NULL,
    [LastUpdatedBy]             VARCHAR (40)     CONSTRAINT [df_UserMainLastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]              DATETIME         CONSTRAINT [df_UserMainLastModified] DEFAULT (getdate()) NULL,
    [IsActive]                  BIT              NULL,
    [StartDate]                 DATETIME         CONSTRAINT [df_UserMainStartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]                   DATETIME         CONSTRAINT [df_UserMainEndtDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_UserMain] PRIMARY KEY CLUSTERED ([Id_Identitycolumn] ASC)
);

