CREATE TABLE [stg].[imis_GroupTypeRef] (
    [GroupTypeKey]                   UNIQUEIDENTIFIER NOT NULL,
    [GroupTypeName]                  NVARCHAR (65)    NOT NULL,
    [IsSystem]                       BIT              CONSTRAINT [DF_GroupTypeRef_IsSystem] DEFAULT ((0)) NOT NULL,
    [IsPaymentRequired]              BIT              CONSTRAINT [DF_GroupTypeRef_IsPaymentRequired] DEFAULT ((0)) NOT NULL,
    [IsDateLimited]                  BIT              CONSTRAINT [DF_GroupTypeRef_IsDateLimited] DEFAULT ((0)) NOT NULL,
    [GroupMemberBranchName]          NVARCHAR (100)   NULL,
    [IsInvitationOnly]               BIT              NOT NULL,
    [DefaultGroupStatusCode]         NVARCHAR (4)     NOT NULL,
    [IsSimpleGroup]                  BIT              CONSTRAINT [DF_GroupTypeRef_IsSimpleGroup] DEFAULT ((0)) NOT NULL,
    [MemberQueryFolderKey]           UNIQUEIDENTIFIER NULL,
    [InheritRolesFlag]               BIT              CONSTRAINT [DF_GroupTypeRef_InheritRolesFlag] DEFAULT ((0)) NOT NULL,
    [IsSingleRole]                   BIT              CONSTRAINT [DF_GroupTypeRef_IsSingleRole] DEFAULT ((0)) NOT NULL,
    [GroupTypeDesc]                  NVARCHAR (250)   NULL,
    [CreatedByUserKey]               UNIQUEIDENTIFIER NOT NULL,
    [UpdatedByUserKey]               UNIQUEIDENTIFIER NOT NULL,
    [CreatedOn]                      DATETIME         NOT NULL,
    [UpdatedOn]                      DATETIME         NOT NULL,
    [LandingPageContentKey]          UNIQUEIDENTIFIER NULL,
    [IsRelationshipGroup]            BIT              CONSTRAINT [DF_GroupTypeRef_IsRelationshipGroup] DEFAULT ((0)) NOT NULL,
    [ExtendActiveMembershipTermFlag] BIT              CONSTRAINT [DF_GroupTypeRef_ExtendActiveMembershipTermFlag] DEFAULT ((0)) NOT NULL,
    [Id_Identitycolumn]              INT              IDENTITY (1, 1) NOT NULL,
    [LastUpdatedBy]                  VARCHAR (40)     CONSTRAINT [df_GroupTypeRef_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]                   DATETIME         CONSTRAINT [df_GroupTypeRef_LastModified] DEFAULT (getdate()) NULL,
    [IsActive]                       BIT              NULL,
    [StartDate]                      DATETIME         CONSTRAINT [df_GroupTypeRef_StartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]                        DATETIME         CONSTRAINT [df_GroupTypeRef_EndtDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_GroupTypeRef] PRIMARY KEY CLUSTERED ([Id_Identitycolumn] ASC),
    CONSTRAINT [AK_GroupTypeRef_GroupTypeName] UNIQUE NONCLUSTERED ([GroupTypeName] ASC)
);

