CREATE TABLE [stg].[imis_Custom_Degree] (
    [ID]                 VARCHAR (10)  DEFAULT ('') NOT NULL,
    [SEQN]               INT           DEFAULT ((0)) NOT NULL,
    [SCHOOL_ID]          VARCHAR (10)  DEFAULT ('') NOT NULL,
    [SCHOOL_OTHER]       VARCHAR (255) DEFAULT ('') NOT NULL,
    [DEGREE_LEVEL]       VARCHAR (10)  DEFAULT ('') NOT NULL,
    [DEGREE_DATE]        DATETIME      NULL,
    [DEGREE_PLANNING]    BIT           DEFAULT ((0)) NOT NULL,
    [MAJOR]              VARCHAR (10)  DEFAULT ('') NOT NULL,
    [ACCREDITED_PROGRAM] VARCHAR (255) DEFAULT ('') NOT NULL,
    [DEGREE_COMPLETE]    BIT           DEFAULT ((0)) NOT NULL,
    [SCHOOL_STUDENT_ID]  VARCHAR (255) DEFAULT ('') NOT NULL,
    [ALL_SCHOOLS]        VARCHAR (255) DEFAULT ('') NOT NULL,
    [ACCRED_SCHOOLS]     VARCHAR (255) DEFAULT ('') NOT NULL,
    [DEGREE_PROGRAM]     VARCHAR (255) DEFAULT ('') NOT NULL,
    [IS_CURRENT]         BIT           DEFAULT ((0)) NOT NULL,
    [SCHOOL_SEQN]        INT           DEFAULT ((0)) NOT NULL,
    [DEGREE_LEVEL_OTHER] VARCHAR (50)  DEFAULT ('') NOT NULL,
    [TIME_STAMP]         BIGINT        NULL,
    [Id_Identitycolumn]  INT           IDENTITY (1, 1) NOT NULL,
    [LastUpdatedBy]      VARCHAR (40)  CONSTRAINT [df_degreeLastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]       DATETIME      CONSTRAINT [df_degreeLastModified] DEFAULT (getdate()) NULL,
    [IsActive]           BIT           NULL,
    [StartDate]          DATETIME      CONSTRAINT [df_degreeStartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]            DATETIME      CONSTRAINT [df_degreeEndtDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_Custom_Degree] PRIMARY KEY CLUSTERED ([Id_Identitycolumn] ASC)
);

