CREATE TABLE [stg].[imis_EP_Metrics_General] (
    [ID]                    VARCHAR (10)  DEFAULT ('') NOT NULL,
    [SEQN]                  INT           DEFAULT ((0)) NOT NULL,
    [COHORT]                INT           DEFAULT ((0)) NOT NULL,
    [MEMBER_TYPE]           VARCHAR (10)  DEFAULT ('') NOT NULL,
    [CATEGORY]              VARCHAR (10)  DEFAULT ('') NOT NULL,
    [STATUS]                VARCHAR (2)   DEFAULT ('') NOT NULL,
    [TRANSACTION_DATE]      DATETIME      NULL,
    [THRU_DATE]             DATETIME      NULL,
    [PROGRAM_YEAR]          INT           DEFAULT ((0)) NOT NULL,
    [SCHOOL_ID]             VARCHAR (10)  DEFAULT ('') NOT NULL,
    [SCHOOL_DEGREE_SEQN]    INT           DEFAULT ((0)) NOT NULL,
    [SCHOOL_NAME]           VARCHAR (255) DEFAULT ('') NOT NULL,
    [DEGREE_PROGRAM]        VARCHAR (255) DEFAULT ('') NOT NULL,
    [DEGREE_LEVEL]          VARCHAR (2)   DEFAULT ('') NOT NULL,
    [PREVIOUSLY_STUDENT]    BIT           DEFAULT ((0)) NOT NULL,
    [PREVIOUSLY_MEMBER]     BIT           DEFAULT ((0)) NOT NULL,
    [JOIN_TYPE]             VARCHAR (10)  DEFAULT ('') NOT NULL,
    [PAN_MEMBER]            BIT           DEFAULT ((0)) NOT NULL,
    [FISCAL_YEAR]           INT           DEFAULT ((0)) NOT NULL,
    [FISCAL_QUARTER]        INT           DEFAULT ((0)) NOT NULL,
    [FISCAL_YEAR_QUARTER]   VARCHAR (25)  DEFAULT ('') NOT NULL,
    [AICP_STATUS]           VARCHAR (5)   DEFAULT ('') NOT NULL,
    [DESIGNATION]           VARCHAR (50)  DEFAULT ('') NOT NULL,
    [SALARY_RANGE]          VARCHAR (10)  DEFAULT ('') NOT NULL,
    [PREVIOUSLY_NEW_MEMBER] BIT           DEFAULT ((0)) NOT NULL,
    [PRIMARY_CHAPTER]       VARCHAR (10)  DEFAULT ('') NOT NULL,
    [TIME_STAMP]            BIGINT        NULL,
    [Id_Identitycolumn]     INT           IDENTITY (1, 1) NOT NULL,
    [LastUpdatedBy]         VARCHAR (40)  CONSTRAINT [df_genLastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]          DATETIME      CONSTRAINT [df_genLastModified] DEFAULT (getdate()) NULL,
    [IsActive]              BIT           NULL,
    [StartDate]             DATETIME      CONSTRAINT [df_genStartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]               DATETIME      CONSTRAINT [df_genEndtDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_EP_Metrics_General] PRIMARY KEY CLUSTERED ([Id_Identitycolumn] ASC)
);

