CREATE TABLE [stg].[imis_ContactMain] (
    [ContactKey]                   UNIQUEIDENTIFIER NOT NULL,
    [ContactStatusCode]            NVARCHAR (2)     NOT NULL,
    [FullName]                     NVARCHAR (110)   NOT NULL,
    [SortName]                     NVARCHAR (110)   NOT NULL,
    [IsInstitute]                  BIT              NOT NULL,
    [TaxIDNumber]                  NVARCHAR (12)    NULL,
    [NoSolicitationFlag]           BIT              NOT NULL,
    [SyncContactID]                VARCHAR (20)     NULL,
    [UpdatedOn]                    DATETIME         NOT NULL,
    [UpdatedByUserKey]             UNIQUEIDENTIFIER NOT NULL,
    [IsIDEditable]                 BIT              NULL,
    [ID]                           NVARCHAR (12)    NULL,
    [PreferredAddressCategoryCode] INT              NOT NULL,
    [IsSortNameOverridden]         BIT              CONSTRAINT [DF_ContactMain_IsSortNameOverridden] DEFAULT ((0)) NOT NULL,
    [PrimaryMembershipGroupKey]    UNIQUEIDENTIFIER NULL,
    [MajorKey]                     NVARCHAR (30)    NULL,
    [AccessKey]                    UNIQUEIDENTIFIER NOT NULL,
    [CreatedByUserKey]             UNIQUEIDENTIFIER NOT NULL,
    [CreatedOn]                    DATETIME         NOT NULL,
    [TextOnlyEmailFlag]            BIT              CONSTRAINT [DF_ContactMain_TextOnlyEmailFlag] DEFAULT ((0)) NOT NULL,
    [ContactTypeKey]               UNIQUEIDENTIFIER NOT NULL,
    [OptOutFlag]                   BIT              CONSTRAINT [DF_ContactMain_OptOutFlag] DEFAULT ((0)) NOT NULL,
    [MarkedForDeleteOn]            DATETIME         NULL,
    [Id_Identitycolumn]            INT              IDENTITY (1, 1) NOT NULL,
    [LastUpdatedBy]                VARCHAR (40)     CONSTRAINT [df_ContactMain_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]                 DATETIME         CONSTRAINT [df_ContactMain_LastModified] DEFAULT (getdate()) NULL,
    [IsActive]                     BIT              NULL,
    [StartDate]                    DATETIME         CONSTRAINT [df_ContactMain_StartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]                      DATETIME         CONSTRAINT [df_ContactMain_EndtDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_ContactMain] PRIMARY KEY CLUSTERED ([Id_Identitycolumn] ASC)
);

