CREATE TABLE [stg].[imis_Order_Meet] (
    [ORDER_NUMBER]            NUMERIC (15, 2) CONSTRAINT [DF_Order_Meet_ORDER_NUMBER] DEFAULT ((0)) NOT NULL,
    [MEETING]                 VARCHAR (10)    CONSTRAINT [DF_Order_Meet_MEETING] DEFAULT ('') NOT NULL,
    [REGISTRANT_CLASS]        VARCHAR (5)     CONSTRAINT [DF_Order_Meet_REGISTRANT_CLASS] DEFAULT ('') NOT NULL,
    [ARRIVAL]                 DATETIME        NULL,
    [DEPARTURE]               DATETIME        NULL,
    [HOTEL]                   VARCHAR (40)    CONSTRAINT [DF_Order_Meet_HOTEL] DEFAULT ('') NOT NULL,
    [LODGING_INSTRUCTIONS]    VARCHAR (255)   CONSTRAINT [DF_Order_Meet_LODGING_INSTRUCTIONS] DEFAULT ('') NOT NULL,
    [BOOTH]                   VARCHAR (255)   CONSTRAINT [DF_Order_Meet_BOOTH] DEFAULT ('') NOT NULL,
    [GUEST_FIRST]             VARCHAR (20)    CONSTRAINT [DF_Order_Meet_GUEST_FIRST] DEFAULT ('') NOT NULL,
    [GUEST_MIDDLE]            VARCHAR (20)    CONSTRAINT [DF_Order_Meet_GUEST_MIDDLE] DEFAULT ('') NOT NULL,
    [GUEST_LAST]              VARCHAR (30)    CONSTRAINT [DF_Order_Meet_GUEST_LAST] DEFAULT ('') NOT NULL,
    [GUEST_IS_SPOUSE]         BIT             CONSTRAINT [DF_Order_Meet_GUEST_IS_SPOUSE] DEFAULT ((0)) NOT NULL,
    [ADDITIONAL_BADGES]       VARCHAR (MAX)   NULL,
    [DELEGATE]                VARCHAR (10)    CONSTRAINT [DF_Order_Meet_DELEGATE] DEFAULT ('') NOT NULL,
    [UF_1]                    BIT             CONSTRAINT [DF_Order_Meet_UF_1] DEFAULT ((0)) NOT NULL,
    [UF_2]                    BIT             CONSTRAINT [DF_Order_Meet_UF_2] DEFAULT ((0)) NOT NULL,
    [UF_3]                    BIT             CONSTRAINT [DF_Order_Meet_UF_3] DEFAULT ((0)) NOT NULL,
    [UF_4]                    BIT             CONSTRAINT [DF_Order_Meet_UF_4] DEFAULT ((0)) NOT NULL,
    [UF_5]                    BIT             CONSTRAINT [DF_Order_Meet_UF_5] DEFAULT ((0)) NOT NULL,
    [UF_6]                    VARCHAR (100)   CONSTRAINT [DF_Order_Meet_UF_6] DEFAULT ('') NOT NULL,
    [UF_7]                    VARCHAR (100)   CONSTRAINT [DF_Order_Meet_UF_7] DEFAULT ('') NOT NULL,
    [UF_8]                    VARCHAR (100)   CONSTRAINT [DF_Order_Meet_UF_8] DEFAULT ('') NOT NULL,
    [SHARE_STATUS]            INT             CONSTRAINT [DF_Order_Meet_SHARE_STATUS] DEFAULT ((0)) NOT NULL,
    [SHARE_ORDER_NUMBER]      NUMERIC (15, 2) CONSTRAINT [DF_Order_Meet_SHARE_ORDER_NUMBER] DEFAULT ((0)) NOT NULL,
    [ROOM_TYPE]               VARCHAR (8)     CONSTRAINT [DF_Order_Meet_ROOM_TYPE] DEFAULT ('') NOT NULL,
    [ROOM_QUANTITY]           INT             CONSTRAINT [DF_Order_Meet_ROOM_QUANTITY] DEFAULT ((0)) NOT NULL,
    [ROOM_CONFIRM]            BIT             CONSTRAINT [DF_Order_Meet_ROOM_CONFIRM] DEFAULT ((0)) NOT NULL,
    [UF_9]                    VARCHAR (MAX)   NULL,
    [UF_10]                   VARCHAR (MAX)   NULL,
    [ARRIVAL_TIME]            DATETIME        NULL,
    [DEPARTURE_TIME]          DATETIME        NULL,
    [COMP_REGISTRATIONS]      INT             CONSTRAINT [DF_Order_Meet_COMP_REGISTRATIONS] DEFAULT ((0)) NOT NULL,
    [COMP_REG_SOURCE]         DECIMAL (15, 6) NULL,
    [TOTAL_SQUARE_FEET]       NUMERIC (15, 2) CONSTRAINT [DF_Order_Meet_TOTAL_SQUARE_FEET] DEFAULT ((0)) NOT NULL,
    [COMP_REGISTRATIONS_USED] INT             CONSTRAINT [DF_Order_Meet_COMP_REGISTRATIONS_USED] DEFAULT ((0)) NOT NULL,
    [PARENT_ORDER_NUMBER]     NUMERIC (15, 2) NULL,
    [REGISTERED_BY_ID]        VARCHAR (10)    NULL,
    [TIME_STAMP]              BIGINT          NULL,
    [LastUpdatedBy]           VARCHAR (40)    CONSTRAINT [df_Order_Meet_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]            DATETIME        CONSTRAINT [df_Order_Meet_LastModified] DEFAULT (getdate()) NULL,
    [IsActive]                BIT             NULL,
    [StartDate]               DATETIME        CONSTRAINT [df_Order_Meet_StartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]                 DATETIME        CONSTRAINT [df_Order_Meet_EndtDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_imis_Order_Meet] PRIMARY KEY NONCLUSTERED ([ORDER_NUMBER] ASC)
);

