CREATE TABLE [stg].[imis_Demo_Recurring_Gift] (
    [ID]                       VARCHAR (10)  DEFAULT ('') NOT NULL,
    [SEQN]                     INT           DEFAULT ((0)) NOT NULL,
    [RG_INITIAL_GIFT_DATE]     DATETIME      NULL,
    [RG_UNIQUE_ID]             VARCHAR (20)  DEFAULT ('') NOT NULL,
    [RG_FREQUENCY]             VARCHAR (20)  DEFAULT ('') NOT NULL,
    [RG_TOTAL_OCCURENCES]      INT           DEFAULT ((0)) NOT NULL,
    [RG_RECURRING_AMOUNT]      MONEY         DEFAULT ((0)) NOT NULL,
    [RG_TOTAL_AMOUNT_EXPECTED] MONEY         DEFAULT ((0)) NOT NULL,
    [RG_NUM_GIFTS_GIVEN]       INT           DEFAULT ((0)) NOT NULL,
    [RG_TOTAL_AMOUNT_GIVEN]    MONEY         DEFAULT ((0)) NOT NULL,
    [RG_DISTRIBUTION]          VARCHAR (31)  DEFAULT ('') NOT NULL,
    [RG_FUND]                  VARCHAR (10)  DEFAULT ('') NOT NULL,
    [RG_CAMPAIGN_CODE]         VARCHAR (10)  DEFAULT ('') NOT NULL,
    [RG_APPEAL_CODE]           VARCHAR (40)  DEFAULT ('') NOT NULL,
    [RG_CC_EXP_MONTH]          INT           DEFAULT ((0)) NOT NULL,
    [RG_CC_EXP_YEAR]           INT           DEFAULT ((0)) NOT NULL,
    [RG_LAST_RESPONSE_DATE]    DATETIME      NULL,
    [RG_CONFIRMATION_NUM]      VARCHAR (32)  DEFAULT ('') NOT NULL,
    [RG_ACTIVE]                BIT           DEFAULT ((0)) NOT NULL,
    [RG_FIN_ACCT_ID]           INT           DEFAULT ((0)) NOT NULL,
    [RG_LAST_STATUS]           VARCHAR (255) DEFAULT ('') NOT NULL,
    [RG_WARNING_FLAG]          BIT           DEFAULT ((0)) NOT NULL,
    [TIME_STAMP]               BIGINT        NULL,
    [RG_PLEDGE_TRANS_NUM]      INT           DEFAULT ((0)) NOT NULL,
    [RG_PLEDGE_LAST_STATUS]    VARCHAR (255) DEFAULT ('') NOT NULL,
    [Id_Identitycolumn]        INT           IDENTITY (1, 1) NOT NULL,
    [LastUpdatedBy]            VARCHAR (40)  CONSTRAINT [df_demogiftLastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastModified]             DATETIME      CONSTRAINT [df_demogiftLastModified] DEFAULT (getdate()) NULL,
    [IsActive]                 BIT           NULL,
    [StartDate]                DATETIME      CONSTRAINT [df_demogiftStartDate] DEFAULT ('1901-01-01 00:00:00') NULL,
    [EndDate]                  DATETIME      CONSTRAINT [df_demogiftEndtDate] DEFAULT ('2999-12-31 00:00:00') NULL,
    CONSTRAINT [PK_Demo_Recurring_Gift] PRIMARY KEY CLUSTERED ([Id_Identitycolumn] ASC)
);

