/****** Script for SelectTopNRows command from SSMS  ******/

CREATE VIEW vw_dimMemberV2 AS
SELECT [MemberIDKey]
      ,[Parent]
      ,[Member_ID]
      ,[First_Name]
      ,[Middle_Name]
      ,[Last_Name]
      ,[Full_Name]
      ,[Email]
      ,[Home_Phone]
      ,[Mobile_Phone]
      ,[Work_Phone]
      ,[Designation]
      ,[Functional_Title]
      ,[Birth_Date]
      ,[JoinDate]
      ,[Cohort]
      ,[LastUpdatedBy]
      ,[LastModified]
      ,[IsActive]
      ,[StartDate]
      ,[EndDate]
      ,[Merged_Date]
      ,[Cohortquarter]
  FROM [rpt].[dimMember]