CREATE VIEW [dbo].[vw_tblFactMember_IS] AS
SELECT [MemberIDKey]
      ,[ProductTypeKey]
      ,[ProductCodeKey]
      ,[MemberTypeIDKey]
      ,[SalaryIDKey]
      ,[RaceIDKey]
      ,[OrgKey]
      ,[ChapterKey]
      ,[Trans_Date_Key]
      ,[Paid_Through_Key]
      ,[Home_Address_Key]
      ,[Work_Address_Key]
      ,[StatusKey]
      ,[MemberStatusKey]
      ,[IsCurrent]
  FROM [rpt].[tblFactMember]