/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW vw_tblFactMember_final_Current AS
SELECT [Member_ID]
      ,[Member_Type]
      ,[SalaryRange]
      ,[RaceID]
      ,[Origin]
      ,[Chapter]
      ,[TransDate]
      ,[Paid_Thru_Date]
      ,[Home_Address_Num]
      ,[Work_Address_Num]
      ,[Status]
      ,[Gender]
      ,[Category]
      ,[Org_Type]
      ,[Member_Status]
      ,[Product_Code]
      ,[Prod_Type]
      ,[Source_Code]
      ,[IsCurrent]
      ,[Complimentary]
  FROM [tmp].[FactMember_Final_Current]